//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace TravelService.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("TravelService.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prihvati.
        /// </summary>
        internal static string Accept {
            get {
                return ResourceManager.GetString("Accept", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prisustvo.
        /// </summary>
        internal static string Attendance {
            get {
                return ResourceManager.GetString("Attendance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najbolje Ture.
        /// </summary>
        internal static string Best_Tours {
            get {
                return ResourceManager.GetString("Best Tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izmedju 18 i 50.
        /// </summary>
        internal static string Between_18_and_50 {
            get {
                return ResourceManager.GetString("Between 18 and 50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkazi Turu.
        /// </summary>
        internal static string Cancel_Tour {
            get {
                return ResourceManager.GetString("Cancel Tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime Kljucne Tacke.
        /// </summary>
        internal static string CheckPoint_Name {
            get {
                return ResourceManager.GetString("CheckPoint Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Grad i drzava.
        /// </summary>
        internal static string City_and_country {
            get {
                return ResourceManager.GetString("City and country", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zatvori.
        /// </summary>
        internal static string Close {
            get {
                return ResourceManager.GetString("Close", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kompleksne Ture.
        /// </summary>
        internal static string Complex_Tours {
            get {
                return ResourceManager.GetString("Complex Tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Napravi .
        /// </summary>
        internal static string Create {
            get {
                return ResourceManager.GetString("Create", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Dodaj Turu.
        /// </summary>
        internal static string Create_Tour {
            get {
                return ResourceManager.GetString("Create Tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj turu za Jezik.
        /// </summary>
        internal static string Create_Tour_for_Language {
            get {
                return ResourceManager.GetString("Create Tour for Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Kreiraj Turu za Lokaciju.
        /// </summary>
        internal static string Create_Tour_for_Location {
            get {
                return ResourceManager.GetString("Create Tour for Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Trenutna Kljucna tacka.
        /// </summary>
        internal static string Current_Checkpoint {
            get {
                return ResourceManager.GetString("Current Checkpoint", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Opis.
        /// </summary>
        internal static string Description {
            get {
                return ResourceManager.GetString("Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Otkaz.
        /// </summary>
        internal static string Dissmisal {
            get {
                return ResourceManager.GetString("Dissmisal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zavrsi Turu.
        /// </summary>
        internal static string End_Tour {
            get {
                return ResourceManager.GetString("End Tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Buduce Ture.
        /// </summary>
        internal static string Future_Tours {
            get {
                return ResourceManager.GetString("Future Tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vrati se nazad.
        /// </summary>
        internal static string Go_back {
            get {
                return ResourceManager.GetString("Go back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Gostiju.
        /// </summary>
        internal static string GUEST_LIST {
            get {
                return ResourceManager.GetString("GUEST LIST", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pocetak.
        /// </summary>
        internal static string Home {
            get {
                return ResourceManager.GetString("Home", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pogresna lokacija selektovana.
        /// </summary>
        internal static string Invalid_location_selected {
            get {
                return ResourceManager.GetString("Invalid location selected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Jezik.
        /// </summary>
        internal static string Language {
            get {
                return ResourceManager.GetString("Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lista Kompleksnih Tura.
        /// </summary>
        internal static string List_of__Complex_Tours {
            get {
                return ResourceManager.GetString("List of  Complex Tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Lokacija.
        /// </summary>
        internal static string Location {
            get {
                return ResourceManager.GetString("Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izloguj se.
        /// </summary>
        internal static string LogOut {
            get {
                return ResourceManager.GetString("LogOut", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Oznaci.
        /// </summary>
        internal static string Mark {
            get {
                return ResourceManager.GetString("Mark", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najtrazeniji Jezik.
        /// </summary>
        internal static string Most_Requested_Language {
            get {
                return ResourceManager.GetString("Most Requested Language", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najtrazenija Lokacija.
        /// </summary>
        internal static string Most_Requested_Location {
            get {
                return ResourceManager.GetString("Most Requested Location", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najposecenije Ture.
        /// </summary>
        internal static string Most_Visited_Tours {
            get {
                return ResourceManager.GetString("Most Visited Tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Najposecenije u izabranaj godini.
        /// </summary>
        internal static string Most_Visited_Tours_in_Selected_Year {
            get {
                return ResourceManager.GetString("Most Visited Tours in Selected Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj gostiju.
        /// </summary>
        internal static string Number_of_guests {
            get {
                return ResourceManager.GetString("Number of guests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Broj zahteva za ture za.
        /// </summary>
        internal static string Number_of_tour_requests_for {
            get {
                return ResourceManager.GetString("Number of tour requests for", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vise od 50.
        /// </summary>
        internal static string Over_50 {
            get {
                return ResourceManager.GetString("Over 50", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prosle Ture.
        /// </summary>
        internal static string Past_Tours {
            get {
                return ResourceManager.GetString("Past Tours", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Profile.
        /// </summary>
        internal static string Profile {
            get {
                return ResourceManager.GetString("Profile", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahtev prihvacen.
        /// </summary>
        internal static string Request_Approved {
            get {
                return ResourceManager.GetString("Request Approved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zahtevi.
        /// </summary>
        internal static string Requests {
            get {
                return ResourceManager.GetString("Requests", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ocene.
        /// </summary>
        internal static string Reviews {
            get {
                return ResourceManager.GetString("Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pretrazi.
        /// </summary>
        internal static string Search {
            get {
                return ResourceManager.GetString("Search", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Izaberi Godinu.
        /// </summary>
        internal static string Select_Year {
            get {
                return ResourceManager.GetString("Select Year", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikazi statistiku za jezik.
        /// </summary>
        internal static string Show_Languge_Statistics {
            get {
                return ResourceManager.GetString("Show Languge Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikazi statistiku za lokacije.
        /// </summary>
        internal static string Show_Location_Statistics {
            get {
                return ResourceManager.GetString("Show Location Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Prikazi ocene.
        /// </summary>
        internal static string Show_Reviews {
            get {
                return ResourceManager.GetString("Show Reviews", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Zapocni.
        /// </summary>
        internal static string Start_Tour {
            get {
                return ResourceManager.GetString("Start Tour", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistike.
        /// </summary>
        internal static string Statistics {
            get {
                return ResourceManager.GetString("Statistics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Statistika.
        /// </summary>
        internal static string Stats {
            get {
                return ResourceManager.GetString("Stats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Predlozi.
        /// </summary>
        internal static string Suggestions {
            get {
                return ResourceManager.GetString("Suggestions", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ime Ture.
        /// </summary>
        internal static string Tour_Name {
            get {
                return ResourceManager.GetString("Tour Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum pocetka.
        /// </summary>
        internal static string Tour_Start_Date {
            get {
                return ResourceManager.GetString("Tour Start Date", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Datum kraja.
        /// </summary>
        internal static string Tour_Start_End {
            get {
                return ResourceManager.GetString("Tour Start End", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ture aktivne danas.
        /// </summary>
        internal static string Tours_that_are_active_today {
            get {
                return ResourceManager.GetString("Tours that are active today", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pocetak.
        /// </summary>
        internal static string TourStart {
            get {
                return ResourceManager.GetString("TourStart", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Ispod 18.
        /// </summary>
        internal static string Under_18 {
            get {
                return ResourceManager.GetString("Under 18", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Korisnicko Ime.
        /// </summary>
        internal static string Username {
            get {
                return ResourceManager.GetString("Username", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SA Vaucerima %.
        /// </summary>
        internal static string With_Voucher__ {
            get {
                return ResourceManager.GetString("With Voucher %", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bez Vaucera %.
        /// </summary>
        internal static string Without_Voucher__ {
            get {
                return ResourceManager.GetString("Without Voucher %", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Moras da izaberes datum koji je u okviru kraja i pocetka ture.
        /// </summary>
        internal static string You_must_select_a_date_within_the_valid_tour_range {
            get {
                return ResourceManager.GetString("You must select a date within the valid tour range", resourceCulture);
            }
        }
    }
}
